[package]
name = "example"
version = "0.1.0"
edition = "2024"

[dependencies]
axial_macros = "0.1.0"
tokio = { version = "1.45.0", features = ["full"] }
axial = { version = "0.1.0", features = ["client"] }
