[package]
name = "axial_macros"
version = "0.1.0"
edition = "2024"

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full", "extra-traits"] }
axial = { path = "../" }

[lib]
proc-macro = true
